/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Anwar
 * @brief          : Learn-in-depth.com
 ******************************************************************************
//		AUTOSAR Door Lock indication Project
 ******************************************************************************/


#include "stm32f103xx.h"
#include "GPIO.h"

#define CYCLES_PER_LOOP 3
void wait_cycles( uint32_t n ) {
	uint32_t l = n/CYCLES_PER_LOOP;
	asm volatile( "0:" "SUBS %[count], 1;" "BNE 0b;" :[count]"+r"(l) );
}


void MCU_init () {

	//==================GPIO INIT =============================

	//Enable CLock
	RCC_GPIOA_CLK_EN();

	//PA3 ---> Door Sensor
	GPIO_pinConfig_t PinCfg_Door_Sensor ;
	PinCfg_Door_Sensor.GPIO_pinNumber = GPIO_PIN_3;
	PinCfg_Door_Sensor.GPIO_mode = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_init(GPIOA, &PinCfg_Door_Sensor);

	//PA7 ---> Led On/OFF

	PinCfg_Door_Sensor.GPIO_pinNumber = GPIO_PIN_7;
	PinCfg_Door_Sensor.GPIO_mode = GPIO_MODE_OUTPUT_PP;
	PinCfg_Door_Sensor.GPIO_output_speed = GPIO_SPEED_10M;
	MCAL_GPIO_init(GPIOA, &PinCfg_Door_Sensor);
}
void StartOS ()
{
	unsigned char i = 0 ;
	//it is not memec 10ms or 12ms
	//it is just a prodic sequence fast implementation
	//as we will focus on implement OS and used accurate time based on the timer later on AUTOSAR OS unit
	//But nw we focused only on APPLICATion Layer
	while (1)
	{
		//memec RTE_Event_10ms
		if (i==10)
		{
			ReadDoorSensor_runnable();
			i++ ;
		}else if (i==12)
		{
			//memec RTE_Event_12ms
			DoorLock_indication_runnable();
			i=0 ;
		}else
		{
			i++ ;
		}
		wait_cycles(10);
	}

}
#define LEDON  0
#define LEDOFF 1

int main(void)
{
	MCU_init();
	StartOS();
	/* Loop forever */
	while(1)
	{



	}
}
